version: '3.7'
services:
    database:
        image: 'mariadb:latest'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: abc_db
        ports:
            - '8003:3306'
